server:
  port: 8086
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/documents
    username: rinklinky
    password: pass
    initialization-mode: ALWAYS
